name: Test and Deploy (Functions Action)

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: mo-test-func
  AZURE_FUNCTION_PROJ_PATH: './src'
  AZURE_FUNCTION_TEST_PATH: './test'
  AZURE_FUNCTION_PUBLISH_PATH: '.'
  DOTNET_VERSION: '6.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Get the latest source code commit
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore
        run: dotnet restore
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Build
        run: dotnet build --no-restore
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}
      
      - name: Publish For Deployment
        run: dotnet publish --no-build --no-restore --configuration Release --output ./publish
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Upload artifact for testing and deployment
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          path: ${{ env.AZURE_FUNCTION_PROJ_PATH }}/publish
      
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get the latest source code commit
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test
        working-directory: ${{ env.AZURE_FUNCTION_TEST_PATH }}

  deploy:

    runs-on: ubuntu-latest
    needs: [build, test]
    environment:
      name: production
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTION_PUBLISH_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}