name: Test and Deploy (Functions Action)

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: mo-test-func # set this to the name of your azure function app resource
  AZURE_FUNCTION_PROJ_PATH: './src'  # set this to the path to your function app project
  AZURE_FUNCTION_TEST_PATH: './test'
  ROOT_SOLUTION_PATH: './'
  DOTNET_VERSION: '6.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Get the latest source code commit
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore
        run: dotnet restore
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Test
        run: dotnet test --no-restore --configuration Release
        working-directory: ${{ env.AZURE_FUNCTION_TEST_PATH }}
      
      - name: Publish For Deployment
        run: dotnet publish --no-build --no-restore --configuration Release --output ./output
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Upload artifact for testing and deployment
        uses: actions/upload-artifact@v3
        with:
          name: mo-test-func
          path: ${{ env.AZURE_FUNCTION_PROJ_PATH }}/output
      
  # test:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: mo-test-func
      
  #     - name: Test
  #       run: dotnet test --no-restore --configuration Release
  #       working-directory: ${{ env.AZURE_FUNCTION_TEST_PATH }}