name: Build-Test-Deploy

on:
  # push:
  #   branches: [ main ]

  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: mo-test-func
  DOTNET_VERSION: '6.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get the latest source code commit
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore Project Dependencies
        run: dotnet restore
        working-directory: '${{ github.workspace }}/src'

      - name: Build Project
        run: dotnet build --no-restore --configuration Release
        working-directory: '${{ github.workspace }}/src'
      

      
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Restore Project Dependencies
        run: dotnet restore
        working-directory: '${{ github.workspace }}/test'

      - name: Build Project
        run: dotnet build --no-restore
        working-directory: '${{ github.workspace }}/test'
      
      - name: Test
        run: dotnet test
        working-directory: '${{ github.workspace }}/test'




      #         - name: Publish For Deployment
      #   run: dotnet publish --no-build --no-restore --configuration Release --output ./output
      #   working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      # - name: Upload artifact for deployment
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: mo-test-func
      #     path: ${{ env.AZURE_FUNCTION_PROJ_PATH }}/output