# This is a basic workflow to help you get started with Actions

name: Build Azure Function App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: golden-ratio-calculator  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src'    # set this to the path to your web app project, defaults to the repository root
  AZURE_FUNCTIONAPP_TEST_PATH: './test' 
  DOTNET_VERSION: '6.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Test function app 
          shell: bash
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_TEST_PATH }}'
            dotnet test 
            popd
